/**
 * Round-14 reconstruction of every decision cited by K0.1 §11's ten rows.
 * A clause references ONE authoritative K0_OBLIGATIONS entry. Repeated references are an index
 * of the same assertion in several decisions, not duplicate obligations or new shared evidence.
 * Read the assertion and target together: different wording earns no second counterexample.
 * Rows name the worksheet citations, not extra scenario attribution. All clauses of each cited
 * decision are reconciled here, even when a row's illustrative headline is narrower.
 *
 * This inventory is authored/reviewed semantic work, NOT mechanically extracted assertions.
 * Source and inventory seals make deletion or source drift require an explicit reconciliation
 * change in review. They cannot prove that a human decomposition is semantically complete.
 */
export interface CitedDecision {
  readonly decision: string;
  readonly rows: readonly number[];
  readonly clauses: readonly { readonly id: string; readonly assertion: string; readonly obligation: string }[];
}
export const CITED_DECISIONS: readonly CitedDecision[] = [
  { decision: "ID-1", rows: [1], clauses: [
    {"id": "ID-1.1", "assertion": "Logical Execution identity is never reissued, including after deletion/GC; recycling storage keys requires a separate logical ID.", "obligation": "R1-f"},
  ] },
  { decision: "ID-2", rows: [1], clauses: [
    {"id": "ID-2.1", "assertion": "Producer namespace participates in create identity; equal raw keys from different producers do not collide.", "obligation": "R1-c1"},
    {"id": "ID-2.2", "assertion": "Producer namespace participates in subsequent input identity at the same destination/key.", "obligation": "R1-e1"},
    {"id": "ID-2.3", "assertion": "Exact create identity/content replay returns its original Execution.", "obligation": "R1-a1"},
    {"id": "ID-2.4", "assertion": "Exact create replay does not ingest input twice.", "obligation": "R1-a3"},
    {"id": "ID-2.5", "assertion": "Same create identity with changed content records a conflict.", "obligation": "R1-b1"},
    {"id": "ID-2.6", "assertion": "A conflicting create never edits accepted content.", "obligation": "R1-b2"},
    {"id": "ID-2.7", "assertion": "Exact subsequent input replay preserves its original acceptance position.", "obligation": "R1-e2"},
    {"id": "ID-2.8", "assertion": "Changed subsequent input content records a conflict.", "obligation": "R1-e3"},
    {"id": "ID-2.9", "assertion": "Rejected input conflict leaves the accepted input content/order unchanged.", "obligation": "R1-e4"},
    {"id": "ID-2.10", "assertion": "The same producer/raw input key at different destinations accepts independent inputs.", "obligation": "R1-i"},
  ] },
  { decision: "ID-6", rows: [1, 3], clauses: [
    {"id": "ID-6.1", "assertion": "Exact accepted create replay returns its receipt.", "obligation": "R1-a2"},
    {"id": "ID-6.2", "assertion": "Distinct producers' accepted creates have distinct receipts.", "obligation": "R1-c2"},
    {"id": "ID-6.3", "assertion": "Distinct request keys' accepted creates have distinct receipts.", "obligation": "R1-d1"},
    {"id": "ID-6.4", "assertion": "A refused create conflict mints no acceptance receipt.", "obligation": "R1-b3"},
    {"id": "ID-6.5", "assertion": "An input replay retains the specific ingress acceptance position.", "obligation": "R1-e2"},
    {"id": "ID-6.6", "assertion": "Dispatch intent has its own boundary/position receipt, not an Activation ID surrogate.", "obligation": "R1-g"},
    {"id": "ID-6.7", "assertion": "Exact accepted Outcome replay returns the original receipt.", "obligation": "R3-a1"},
    {"id": "ID-6.8", "assertion": "Different accepted Outcomes have different receipts.", "obligation": "R3-d1"},
    {"id": "ID-6.9", "assertion": "A conflicting Outcome mints no acceptance receipt.", "obligation": "R3-b3"},
    {"id": "ID-6.10", "assertion": "A malformed Outcome mints no acceptance receipt.", "obligation": "R3-c8"},
    {"id": "ID-6.11", "assertion": "A cancellation-losing submission mints no acceptance receipt.", "obligation": "R7-a9"},
    {"id": "ID-6.12", "assertion": "Replay of the cancellation loser mints no receipt.", "obligation": "R7-b"},
    {"id": "ID-6.13", "assertion": "A stale writer rejection mints no receipt.", "obligation": "R10-a2"},
    {"id": "ID-6.14", "assertion": "Effect admission has a boundary-scoped acceptance receipt.", "obligation": "R4-b1"},
    {"id": "ID-6.15", "assertion": "Effect settlement has a separate boundary-scoped receipt.", "obligation": "R4-b2"},
    {"id": "ID-6.16", "assertion": "Child operation acceptance has its own receipt.", "obligation": "R4-b3"},
    {"id": "ID-6.17", "assertion": "Message operation acceptance has its own receipt.", "obligation": "R4-b4"},
    {"id": "ID-6.18", "assertion": "A receipt is evidence only of its own boundary, never of subsequent Effect success.", "obligation": "R1-h"},
  ] },
  { decision: "ID-7", rows: [1], clauses: [
    {"id": "ID-7.1", "assertion": "Creation/input receipt identity is per accepted request, not a single Execution-wide receipt.", "obligation": "R1-a2"},
    {"id": "ID-7.2", "assertion": "Dispatch-intent receipt is independent of the ingress/Outcome receipts.", "obligation": "R1-g"},
    {"id": "ID-7.3", "assertion": "Outcome acceptance positions remain distinct even within one Execution.", "obligation": "R3-d1"},
    {"id": "ID-7.4", "assertion": "Effect admission is a different receipt authority/boundary.", "obligation": "R4-b1"},
    {"id": "ID-7.5", "assertion": "Effect settlement is a different receipt authority/boundary.", "obligation": "R4-b2"},
    {"id": "ID-7.6", "assertion": "Child acceptance is a separately inspectable operation boundary.", "obligation": "R4-b3"},
    {"id": "ID-7.7", "assertion": "Message acceptance is a separately inspectable operation boundary.", "obligation": "R4-b4"},
  ] },
  { decision: "ID-3", rows: [2], clauses: [
    {"id": "ID-3.1", "assertion": "A genuinely new resolved-then-dispatched semantic exchange receives a new Activation ID.", "obligation": "R2-a"},
    {"id": "ID-3.2", "assertion": "Dispatch pins the accepted Event batch; later mailbox arrivals cannot join it.", "obligation": "R2-b1"},
    {"id": "ID-3.3", "assertion": "The dispatched Runtime input and base progress revision remain pinned for the unresolved exchange.", "obligation": "R2-e1"},
    {"id": "ID-3.4", "assertion": "Ordinary redelivery preserves Activation identity.", "obligation": "R2-d1"},
    {"id": "ID-3.5", "assertion": "Ordinary redelivery preserves writer epoch.", "obligation": "R2-d2"},
    {"id": "ID-3.6", "assertion": "Ordinary redelivery preserves immutable batch input.", "obligation": "R2-d3"},
    {"id": "ID-3.7", "assertion": "Authorized takeover preserves Activation identity.", "obligation": "R2-c1"},
    {"id": "ID-3.8", "assertion": "Authorized takeover advances writer epoch.", "obligation": "R2-c2"},
    {"id": "ID-3.9", "assertion": "Authorized takeover preserves immutable batch input.", "obligation": "R2-c3"},
    {"id": "ID-3.10", "assertion": "Takeover requires authentication/recovery permission; epoch value or liveness alone is no credential.", "obligation": "R2-e2"},
  ] },
  { decision: "ID-4", rows: [2], clauses: [
    {"id": "ID-4.1", "assertion": "A takeover advances the ordered fencing value within the unresolved exchange.", "obligation": "R2-c2"},
    {"id": "ID-4.2", "assertion": "An ordinary retry never advances the attempt.", "obligation": "R2-d2"},
    {"id": "ID-4.3", "assertion": "Old-epoch submission is rejected after takeover.", "obligation": "R2-c4"},
    {"id": "ID-4.4", "assertion": "No cross-exchange epoch relation or concrete token spelling is imposed.", "obligation": "R2-e3"},
  ] },
  { decision: "ID-9", rows: [2], clauses: [
    {"id": "ID-9.1", "assertion": "Case 1 redelivery retains exchange ID.", "obligation": "R2-d1"},
    {"id": "ID-9.2", "assertion": "Case 1 redelivery retains epoch and does not make that attempt stale.", "obligation": "R2-d2"},
    {"id": "ID-9.3", "assertion": "Case 1 redelivery retains batch.", "obligation": "R2-d3"},
    {"id": "ID-9.4", "assertion": "Case 2 takeover retains exchange ID.", "obligation": "R2-c1"},
    {"id": "ID-9.5", "assertion": "Case 2 replacement attempt advances epoch.", "obligation": "R2-c2"},
    {"id": "ID-9.6", "assertion": "Case 2 replacement input remains immutable.", "obligation": "R2-c3"},
    {"id": "ID-9.7", "assertion": "Case 2 lease/recovery authorization is distinct from wait/Execution clocks and host death.", "obligation": "R5-h3"},
    {"id": "ID-9.8", "assertion": "Case 3 stale old epoch is refused under the same still-correct Activation ID.", "obligation": "R2-c4"},
    {"id": "ID-9.9", "assertion": "Case 4 a later semantic exchange has a different ID.", "obligation": "R2-a"},
    {"id": "ID-9.10", "assertion": "Case 4 an old exchange cannot be revived by a new-content submission.", "obligation": "R2-e4"},
  ] },
  { decision: "B-1", rows: [2, 5], clauses: [
    {"id": "B-1.1", "assertion": "Reservation pins a finite enumerable set of accepted Event references, not a global cursor.", "obligation": "R2-b1"},
    {"id": "B-1.2", "assertion": "A later accepted Outcome accounts for the entire reserved batch.", "obligation": "R2-b2"},
    {"id": "B-1.3", "assertion": "Acknowledgment stops at the reserved set.", "obligation": "R2-b3"},
    {"id": "B-1.4", "assertion": "A timeout is an Event and is the mandatory deadline-batch member.", "obligation": "R5-e2"},
    {"id": "B-1.5", "assertion": "No batch member lies outside accepted Events and no legal dispatch bound is below one.", "obligation": "R5-j1"},
  ] },
  { decision: "B-2", rows: [2, 5, 6], clauses: [
    {"id": "B-2.1", "assertion": "Ordinary readiness selects retained unacknowledged backlog in bounded acceptance order.", "obligation": "R5-j2"},
    {"id": "B-2.2", "assertion": "Event-triggered readiness excludes ineligible backlog and reserves at least the earliest eligible member.", "obligation": "R5-e1"},
    {"id": "B-2.3", "assertion": "Deadline-triggered readiness retains its mandatory timeout ahead of ineligible backlog.", "obligation": "R5-e2"},
    {"id": "B-2.4", "assertion": "After the mandatory member, eligible Events present at reservation fill the remaining slots.", "obligation": "R5-j3"},
    {"id": "B-2.5", "assertion": "WAITING never dispatches a batch; eligibility ends the wait before selection.", "obligation": "R5-j4"},
    {"id": "B-2.6", "assertion": "Accepted readiness and mailbox truth survive the applicable pre-reservation crash window.", "obligation": "R5-i1"},
    {"id": "B-2.7", "assertion": "Cancellation after wait retirement before reservation explicitly disposes the timeout rather than dispatching it.", "obligation": "R5-k7"},
    {"id": "B-2.8", "assertion": "Ordinary continue with an empty mailbox permits an empty reserved batch.", "obligation": "R5-j2b"},
    {"id": "B-2.9", "assertion": "Selected union members are presented in per-Execution acceptance order, including eligible Events accepted after the wake.", "obligation": "R5-j3b"},
  ] },
  { decision: "B-3", rows: [5, 8], clauses: [
    {"id": "B-3.1", "assertion": "Acceptance acknowledges the whole pinned batch, including timeout Events.", "obligation": "R2-b2"},
    {"id": "B-3.2", "assertion": "Acknowledgment never extends into unreserved backlog.", "obligation": "R2-b3"},
    {"id": "B-3.3", "assertion": "Reservation alone never acknowledges an Event.", "obligation": "R5-j5"},
    {"id": "B-3.4", "assertion": "A losing Outcome acknowledges none of its reserved batch.", "obligation": "R7-a4"},
    {"id": "B-3.5", "assertion": "Acknowledgment is accounting, not semantic obedience; Kernel never parses progress to establish obedience.", "obligation": "R5-j6"},
    {"id": "B-3.6", "assertion": "A Runtime choosing to ignore acknowledged input records that choice in its own progress.", "obligation": "R5-j7"},
  ] },
  { decision: "B-4", rows: [5, 6], clauses: [
    {"id": "B-4.1", "assertion": "An input arriving during computation stays queued for a later batch.", "obligation": "R6-a2"},
    {"id": "B-4.2", "assertion": "Unreserved input is never acknowledged by a global cursor.", "obligation": "R2-b3"},
    {"id": "B-4.3", "assertion": "Unconsumed input receives an explicit terminal disposition rather than disappearing.", "obligation": "R8-b1b"},
    {"id": "B-4.4", "assertion": "Ineligible backlog stays outside a wait-ended batch.", "obligation": "R5-e1"},
    {"id": "B-4.5", "assertion": "After wait-ended readiness is consumed, retained backlog is an ordinary candidate again.", "obligation": "R5-j2"},
    {"id": "B-4.6", "assertion": "An Event accepted during computation cannot join its already-pinned batch.", "obligation": "R6-a1"},
  ] },
  { decision: "B-5", rows: [5, 8], clauses: [
    {"id": "B-5.1", "assertion": "Terminal input disposition is never silently treated as acknowledgment.", "obligation": "R8-b"},
    {"id": "B-5.2", "assertion": "Every unacknowledged input gets a recorded terminal disposition, not deletion.", "obligation": "R8-b1b"},
    {"id": "B-5.3", "assertion": "This includes the reserved batch of a cancellation loser.", "obligation": "R7-c2"},
    {"id": "B-5.4", "assertion": "Retrying that loser returns the recorded rejection without changing the winner.", "obligation": "R7-b2"},
    {"id": "B-5.5", "assertion": "The terminal disposition rule includes the cancellation loser reserved batch.", "obligation": "R8-b2"},
  ] },
  { decision: "B-6", rows: [5], clauses: [
    {"id": "B-6.1", "assertion": "Path A checks already accepted eligible dependency Events at Outcome acceptance.", "obligation": "R5-c2"},
    {"id": "B-6.2", "assertion": "Path A applies also to empty-dependency subscription waits.", "obligation": "R5-c2b"},
    {"id": "B-6.3", "assertion": "Path A retires the accepted deadline in the same Outcome boundary.", "obligation": "R5-d4"},
    {"id": "B-6.4", "assertion": "Path B retires the live registration and becomes ready at eligible Event acceptance, without an Outcome.", "obligation": "R5-d1"},
    {"id": "B-6.5", "assertion": "Path B clears the accepted deadline at Event acceptance.", "obligation": "R5-d6"},
    {"id": "B-6.6", "assertion": "The next reservation uses the retired selector so unrelated backlog cannot displace the wake.", "obligation": "R5-e1"},
    {"id": "B-6.7", "assertion": "Effect settlement owns its own Event/readiness atomic boundary.", "obligation": "R5-i2"},
    {"id": "B-6.8", "assertion": "Child source routing obligation does not itself make the destination ready.", "obligation": "R5-i3"},
    {"id": "B-6.9", "assertion": "Child routing recovery preserves identity and commits readiness at destination acceptance.", "obligation": "R5-i4"},
    {"id": "B-6.10", "assertion": "Message/routed Event acceptance, not source intent creation, owns destination readiness; single-transaction profiles remain permitted.", "obligation": "R5-i5"},
    {"id": "B-6.11", "assertion": "No path depends on a later unjournaled wake write to survive a crash.", "obligation": "R5-i1"},
  ] },
  { decision: "B-7", rows: [5], clauses: [
    {"id": "B-7.1", "assertion": "Path A collapses an already-due deadline inside Outcome acceptance.", "obligation": "R5-c3"},
    {"id": "B-7.2", "assertion": "Path A leaves no accepted live deadline.", "obligation": "R5-c5"},
    {"id": "B-7.3", "assertion": "Path B retires the current generation at Kernel timeout acceptance.", "obligation": "R5-d2"},
    {"id": "B-7.4", "assertion": "Path B clears the accepted deadline.", "obligation": "R5-d5"},
    {"id": "B-7.5", "assertion": "Exactly one timeout Event is created for a generation.", "obligation": "R5-f2a"},
    {"id": "B-7.6", "assertion": "Repeated expiry creates no second readiness/logical timeout.", "obligation": "R5-f2b"},
    {"id": "B-7.7", "assertion": "The immediately resulting batch must include the generation's timeout even at bound one.", "obligation": "R5-e2"},
    {"id": "B-7.8", "assertion": "Timeout delivery is mandatory by construction, not eligibility through a selector or subscription.", "obligation": "R5-b4"},
    {"id": "B-7.9", "assertion": "A later correlated result remains an accepted fact, not voided by timeout.", "obligation": "R5-f3"},
    {"id": "B-7.10", "assertion": "Timeout proves no external action failure.", "obligation": "R5-h4"},
    {"id": "B-7.11", "assertion": "Timeout/readiness acceptance survives crashes on either boundary.", "obligation": "R5-i1"},
  ] },
  { decision: "B-8", rows: [5, 6], clauses: [
    {"id": "B-8.1", "assertion": "Ingress while RUNNING creates no wait-ended readiness.", "obligation": "R6-b1"},
    {"id": "B-8.2", "assertion": "Ingress while READY cannot arm a second readiness.", "obligation": "R6-b2"},
    {"id": "B-8.3", "assertion": "Terminal ordinary input is refused, not fabricated as a new wake.", "obligation": "R6-b3"},
    {"id": "B-8.4", "assertion": "No wait-ended readiness exists without a retirement, or outside READY.", "obligation": "R5-j8"},
    {"id": "B-8.5", "assertion": "Reservation consumes readiness; it cannot re-arm or span exchanges.", "obligation": "R5-j9"},
    {"id": "B-8.6", "assertion": "Takeover reuses the pinned batch rather than reselecting via old readiness.", "obligation": "R2-c3"},
    {"id": "B-8.7", "assertion": "Readiness carries no per-alternative satisfied flag.", "obligation": "R5-d3"},
    {"id": "B-8.8", "assertion": "Crash recovery reconstructs accepted readiness before reservation.", "obligation": "R5-i1"},
  ] },
  { decision: "CL-1", rows: [5], clauses: [
    {"id": "CL-1.1", "assertion": "Wait deadline, Execution deadline and scheduler lease remain three independent identities.", "obligation": "R5-h1"},
    {"id": "CL-1.2", "assertion": "Execution deadline expiry initiates logical cancellation without implying native interruption.", "obligation": "R5-h2"},
    {"id": "CL-1.3", "assertion": "Lease expiry triggers recovery inspection, not proof of host death or unchecked write authority.", "obligation": "R5-h3"},
    {"id": "CL-1.4", "assertion": "Wait expiry ends the registration rather than terminating the Execution.", "obligation": "R5-d2"},
  ] },
  { decision: "CL-2", rows: [5], clauses: [
    {"id": "CL-2.1", "assertion": "Wait timeout and later correlated result remain separate accepted mailbox facts.", "obligation": "R5-f3"},
    {"id": "CL-2.2", "assertion": "Wait timeout is not external failure or proof of non-execution.", "obligation": "R5-h4"},
  ] },
  { decision: "CL-3", rows: [5], clauses: [
    {"id": "CL-3.1", "assertion": "Registration evaluates already-due deadlines before durable WAITING.", "obligation": "R5-c3"},
    {"id": "CL-3.2", "assertion": "Current-generation expiry while WAITING ends that registration.", "obligation": "R5-d2"},
    {"id": "CL-3.3", "assertion": "Superseded timer cannot wake a replacement.", "obligation": "R5-f1a"},
    {"id": "CL-3.4", "assertion": "Superseded timer cannot retire a replacement.", "obligation": "R5-f1a2"},
    {"id": "CL-3.5", "assertion": "Superseded timer cannot mint a timeout.", "obligation": "R5-f1b"},
    {"id": "CL-3.6", "assertion": "Superseded timer cannot clear the replacement's accepted deadline.", "obligation": "R5-f4"},
    {"id": "CL-3.7", "assertion": "No third clock-reading point is introduced.", "obligation": "R5-h5"},
    {"id": "CL-3.8", "assertion": "Registration uses one accepted-time observation.", "obligation": "R5-c6"},
    {"id": "CL-3.9", "assertion": "Due comparison is non-strict at equal instants.", "obligation": "R5-c7"},
  ] },
  { decision: "W-1", rows: [5], clauses: [
    {"id": "W-1.1", "assertion": "Both lists empty is malformed.", "obligation": "R5-a1"},
    {"id": "W-1.2", "assertion": "A deadline cannot rescue two empty lists.", "obligation": "R5-a1b"},
    {"id": "W-1.3", "assertion": "Every alternative supplies at least one selector field.", "obligation": "R5-a2"},
    {"id": "W-1.4", "assertion": "A supplied empty kind set is malformed, distinct from absence.", "obligation": "R5-a3"},
    {"id": "W-1.5", "assertion": "Every subscription is a finite declarative identity; spelling is implementation-owned.", "obligation": "R5-a4"},
    {"id": "W-1.6", "assertion": "Structurally valid inert alternatives count; no satisfiability/deadlock guarantee is added.", "obligation": "R5-a5"},
    {"id": "W-1.7", "assertion": "Subscription-only waits are first-class.", "obligation": "R5-a6"},
    {"id": "W-1.8", "assertion": "Application input wakes only through its declared subscription.", "obligation": "R5-b1"},
    {"id": "W-1.9", "assertion": "A dependency alternative cannot make application input eligible.", "obligation": "R5-b2"},
    {"id": "W-1.10", "assertion": "Inert matching does not acknowledge the application input.", "obligation": "R5-b2b"},
    {"id": "W-1.11", "assertion": "Ordinary Kernel Events use dependency alternatives, with all supplied fields conjunctive.", "obligation": "R5-b3"},
    {"id": "W-1.12", "assertion": "Exact Event identity and finite kind-set membership obey equality; no other selector operator or field is implied.", "obligation": "R5-k1"},
    {"id": "W-1.13", "assertion": "Alternatives combine by ANY-OF, with no privileged list position.", "obligation": "R5-k2"},
    {"id": "W-1.14", "assertion": "Timeout Events are outside both eligibility lists.", "obligation": "R5-b4"},
    {"id": "W-1.15", "assertion": "Any eligible wake retires the whole registration.", "obligation": "R5-d1"},
    {"id": "W-1.16", "assertion": "No satisfaction flag survives; Runtime re-registers outstanding needs.", "obligation": "R5-d3"},
    {"id": "W-1.17", "assertion": "Target wait shape has no callback, payload selector, interleave or Runtime-local work arm.", "obligation": "R5-k3"},
    {"id": "W-1.18", "assertion": "A matching non-first kind-set member retires the wait.", "obligation": "R5-k1b"},
  ] },
  { decision: "W-2", rows: [5, 6], clauses: [
    {"id": "W-2.1", "assertion": "Own-batch acknowledgment precedes the mailbox check.", "obligation": "R5-c1"},
    {"id": "W-2.2", "assertion": "Already accepted eligible dependency Events end registration immediately.", "obligation": "R5-c2"},
    {"id": "W-2.3", "assertion": "Empty dependency lists do not bypass the mailbox check.", "obligation": "R5-c2b"},
    {"id": "W-2.4", "assertion": "Event-triggered retirement creates no timeout.", "obligation": "R5-c2c"},
    {"id": "W-2.5", "assertion": "Immediate Event retirement clears the accepted deadline.", "obligation": "R5-d4"},
    {"id": "W-2.6", "assertion": "Only when no Event is eligible, an already-due deadline collapses before persisting WAITING.", "obligation": "R5-c3"},
    {"id": "W-2.7", "assertion": "Deadline collapse retains no accepted live deadline.", "obligation": "R5-c5"},
    {"id": "W-2.8", "assertion": "The accepted-time observation is taken once in the transaction.", "obligation": "R5-c6"},
    {"id": "W-2.9", "assertion": "Equality with that instant is due.", "obligation": "R5-c7"},
    {"id": "W-2.10", "assertion": "Otherwise WAITING persists with its generation and deadline.", "obligation": "R5-c4"},
    {"id": "W-2.11", "assertion": "Whole-envelope rejection cannot partially commit progress.", "obligation": "R3-c1"},
    {"id": "W-2.12", "assertion": "Whole-envelope rejection cannot acknowledge input.", "obligation": "R3-c2"},
    {"id": "W-2.13", "assertion": "Whole-envelope rejection cannot leak readiness from premature mailbox evaluation.", "obligation": "R3-c7"},
    {"id": "W-2.14", "assertion": "The ordered evaluation is one accepted boundary across crash recovery, not four separately durable commits.", "obligation": "R5-i1"},
  ] },
  { decision: "W-3", rows: [5, 6], clauses: [
    {"id": "W-3.1", "assertion": "Every registration has an independent generation identity, separate from Execution/Activation namespaces.", "obligation": "R5-k4"},
    {"id": "W-3.2", "assertion": "A superseded timer never wakes the current generation.", "obligation": "R5-f1a"},
    {"id": "W-3.3", "assertion": "A superseded timer never retires the current generation.", "obligation": "R5-f1a2"},
    {"id": "W-3.4", "assertion": "A superseded timer never creates a timeout Event.", "obligation": "R5-f1b"},
    {"id": "W-3.5", "assertion": "A superseded timer never clears current accepted deadline state.", "obligation": "R5-f4"},
    {"id": "W-3.6", "assertion": "Authenticated result Events are not generation-fenced.", "obligation": "R5-f3"},
    {"id": "W-3.7", "assertion": "No live generation survives outside WAITING, including immediate registration retirement and terminal decisions.", "obligation": "R5-j8"},
  ] },
  { decision: "W-4", rows: [5], clauses: [
    {"id": "W-4.1", "assertion": "Local work leaves the Activation unresolved RUNNING with no Outcome yet.", "obligation": "R5-g"},
    {"id": "W-4.2", "assertion": "Local work allocates no Kernel wait/generation record.", "obligation": "R5-g2"},
    {"id": "W-4.3", "assertion": "Target protocol has no Runtime-local wait arm or native work identity.", "obligation": "R5-k3"},
    {"id": "W-4.4", "assertion": "Legacy resumption bookkeeping may remain private inside the compatibility Runtime, never shape the Kernel wait.", "obligation": "R5-k5"},
  ] },
  { decision: "W-5", rows: [5], clauses: [
    {"id": "W-5.1", "assertion": "The target wait has no interleave field or implicit wake predicate.", "obligation": "R5-k3"},
    {"id": "W-5.2", "assertion": "A wake does not satisfy a privileged primary dependency; needed work is re-registered.", "obligation": "R5-d3"},
    {"id": "W-5.3", "assertion": "Existing legacy interleave behavior is preserved privately until explicit migration/refusal.", "obligation": "R5-k5"},
  ] },
  { decision: "W-6", rows: [5], clauses: [
    {"id": "W-6.1", "assertion": "Case 1 local work alone stays RUNNING.", "obligation": "R5-g"},
    {"id": "W-6.2", "assertion": "Case 1 creates no wait or generation.", "obligation": "R5-g2"},
    {"id": "W-6.3", "assertion": "Case 2 G1 timer cannot wake G2.", "obligation": "R5-f1a"},
    {"id": "W-6.4", "assertion": "Case 2 G1 timer cannot retire G2.", "obligation": "R5-f1a2"},
    {"id": "W-6.5", "assertion": "Case 3 later result remains a mailbox fact despite timeout/replacement.", "obligation": "R5-f3"},
    {"id": "W-6.6", "assertion": "Case 3 result accepted while READY creates no second readiness.", "obligation": "R6-b2"},
    {"id": "W-6.7", "assertion": "Case 4 a later correlated registration finds already-accepted unacknowledged result.", "obligation": "R5-c2"},
    {"id": "W-6.8", "assertion": "Case 4 registration/reservation does not itself acknowledge that result.", "obligation": "R5-j5"},
  ] },
  { decision: "W-7", rows: [5], clauses: [
    {"id": "W-7.1", "assertion": "Cases 1/2 either correlated alternative can wake, including an early match in the last position.", "obligation": "R5-k2"},
    {"id": "W-7.2", "assertion": "Case 1 an unrelated third correlation must not over-match.", "obligation": "R5-b3"},
    {"id": "W-7.3", "assertion": "Case 3 unsubscribed ordinary input cannot wake.", "obligation": "R5-b1"},
    {"id": "W-7.4", "assertion": "Cases 3/6 ineligible input is not acknowledged.", "obligation": "R5-b2b"},
    {"id": "W-7.5", "assertion": "Cases 3/6 ineligible input remains queued.", "obligation": "R6-a2"},
    {"id": "W-7.6", "assertion": "Cases 4/7 subscribed correction retires the wait.", "obligation": "R5-d1"},
    {"id": "W-7.7", "assertion": "Case 4 outstanding dependencies are re-registered, never marked satisfied by correction.", "obligation": "R5-d3"},
    {"id": "W-7.8", "assertion": "Case 5 the next batch excludes unmatched backlog.", "obligation": "R5-e1"},
    {"id": "W-7.9", "assertion": "Case 5 acknowledgment does not consume excluded backlog.", "obligation": "R2-b3"},
    {"id": "W-7.10", "assertion": "Case 6 matching an application-input dependency alternative is inert.", "obligation": "R5-b2"},
    {"id": "W-7.11", "assertion": "Case 7 a declared matching subscription makes that input eligible.", "obligation": "R5-b1"},
  ] },
  { decision: "W-8", rows: [5], clauses: [
    {"id": "W-8.1", "assertion": "W0 with no dependencies and a continue subscription is valid.", "obligation": "R5-a6"},
    {"id": "W-8.2", "assertion": "Case 1 an early subscribed input is found at registration even with an empty dependency list.", "obligation": "R5-c2b"},
    {"id": "W-8.3", "assertion": "Case 1 an already-due deadline collapses if no eligible input exists.", "obligation": "R5-c3"},
    {"id": "W-8.4", "assertion": "Case 2 unrelated input does not wake W0.", "obligation": "R5-b1"},
    {"id": "W-8.5", "assertion": "Case 2 unmatched input is not acknowledged.", "obligation": "R2-b3"},
    {"id": "W-8.6", "assertion": "Case 2 unmatched input stays queued.", "obligation": "R6-a2"},
    {"id": "W-8.7", "assertion": "Case 3 subscribed input retires W0 at ingress.", "obligation": "R5-d1"},
    {"id": "W-8.8", "assertion": "Case 3 ingress clears the accepted deadline without an Outcome.", "obligation": "R5-d6"},
    {"id": "W-8.9", "assertion": "Case 4 at bound one the wake is not displaced by earlier unrelated input.", "obligation": "R5-e1"},
    {"id": "W-8.10", "assertion": "Case 4 reservation consumes readiness for exactly one exchange.", "obligation": "R5-j9"},
    {"id": "W-8.11", "assertion": "Case 4 later ordinary readiness can select retained backlog.", "obligation": "R5-j2"},
    {"id": "W-8.12", "assertion": "Case 5 completing after subscription wait does not acknowledge excluded backlog.", "obligation": "R8-b"},
    {"id": "W-8.13", "assertion": "Case 5 completion records terminal disposition for excluded backlog.", "obligation": "R8-b1b"},
    {"id": "W-8.14", "assertion": "Case 6 subscription-only deadline still has a mandatory timeout Event, independent of matching.", "obligation": "R5-e2"},
    {"id": "W-8.15", "assertion": "No fake dependency is required and no intent/satisfiability checker is imposed.", "obligation": "R5-a5"},
  ] },
  { decision: "W-9", rows: [5], clauses: [
    {"id": "W-9.1", "assertion": "A timeout is an accepted Event mandatory in the immediately resulting batch.", "obligation": "R5-e2"},
    {"id": "W-9.2", "assertion": "Timeout identity is stable with destination, semantic timeout class and exact generation correlation.", "obligation": "R5-k6"},
    {"id": "W-9.3", "assertion": "Trusted Kernel timer provenance is required, never application or Runtime assertion.", "obligation": "R5-i6"},
    {"id": "W-9.4", "assertion": "Exactly one timeout Event exists per generation despite duplicate delivery.", "obligation": "R5-f2a"},
    {"id": "W-9.5", "assertion": "Duplicate delivery creates no second readiness or logical timeout.", "obligation": "R5-f2b"},
    {"id": "W-9.6", "assertion": "A timeout needs no matching alternative/subscription.", "obligation": "R5-b4"},
    {"id": "W-9.7", "assertion": "Kernel timeout acceptance creates no seventh external receipt boundary.", "obligation": "R5-i7"},
    {"id": "W-9.8", "assertion": "Terminal cancellation before reservation suppresses dispatch and explicitly disposes the timeout.", "obligation": "R5-k7"},
    {"id": "W-9.9", "assertion": "Timeout never proves non-execution or external failure.", "obligation": "R5-h4"},
    {"id": "W-9.10", "assertion": "Case 1 bound-one backlog cannot displace timeout.", "obligation": "R5-e2"},
    {"id": "W-9.11", "assertion": "Case 2 stale timer cannot wake replacement.", "obligation": "R5-f1a"},
    {"id": "W-9.12", "assertion": "Case 2 stale timer cannot retire replacement.", "obligation": "R5-f1a2"},
    {"id": "W-9.13", "assertion": "Case 2 stale timer mints no Event.", "obligation": "R5-f1b"},
    {"id": "W-9.14", "assertion": "Case 3 timeout-then-result preserves the result.", "obligation": "R5-f3"},
    {"id": "W-9.15", "assertion": "Case 3 result before reservation cannot create a second readiness.", "obligation": "R6-b2"},
    {"id": "W-9.16", "assertion": "Case 3 bound-two union includes later eligible result in acceptance order.", "obligation": "R5-j3"},
    {"id": "W-9.17", "assertion": "Case 4 result-first retires the wait.", "obligation": "R5-d1"},
    {"id": "W-9.18", "assertion": "Case 4 timer after Event retirement creates no timeout.", "obligation": "R5-f1b"},
    {"id": "W-9.19", "assertion": "Case 5 already-due registration collapses if no eligible Event exists.", "obligation": "R5-c3"},
    {"id": "W-9.20", "assertion": "Case 5 an already-accepted eligible Event wins with no timeout.", "obligation": "R5-c2c"},
    {"id": "W-9.21", "assertion": "Case 6 repeated expiry creates no second timeout.", "obligation": "R5-f2a"},
    {"id": "W-9.22", "assertion": "Case 6 repeated expiry creates no second readiness before/after reservation.", "obligation": "R5-f2b"},
    {"id": "W-9.23", "assertion": "Subscription spelling remains K1.3-owned rather than an invented validity rule.", "obligation": "R5-a4"},
    {"id": "W-9.24", "assertion": "Cancellation before reservation clears pending timeout readiness.", "obligation": "R5-k7b"},
  ] },
  { decision: "OA-1", rows: [3], clauses: [
    {"id": "OA-1.1", "assertion": "Authenticate submitter before content inspection.", "obligation": "R3-e1"},
    {"id": "OA-1.2", "assertion": "Scope authenticated access to the named Execution before content inspection.", "obligation": "R3-e2"},
  ] },
  { decision: "OA-2", rows: [3], clauses: [
    {"id": "OA-2.1", "assertion": "Exact accepted duplicate returns the original receipt.", "obligation": "R3-a1"},
    {"id": "OA-2.2", "assertion": "Exact duplicate does not rerun the acceptance transaction.", "obligation": "R3-a2"},
    {"id": "OA-2.3", "assertion": "Exact duplicate does not republish emissions.", "obligation": "R3-a3"},
    {"id": "OA-2.4", "assertion": "Exact accepted duplicate does not redispatch Effects.", "obligation": "R3-f2"},
    {"id": "OA-2.5", "assertion": "Changed canonical content under the same identity is a conflict.", "obligation": "R3-b"},
    {"id": "OA-2.6", "assertion": "Conflicting content is never merged/patched.", "obligation": "R3-b2"},
    {"id": "OA-2.7", "assertion": "Replay precedes validation even after policy changes.", "obligation": "R3-f1"},
    {"id": "OA-2.8", "assertion": "Never-accepted cancellation loser replays its rejection, not an accepted receipt.", "obligation": "R7-b2"},
  ] },
  { decision: "OA-3", rows: [3, 7], clauses: [
    {"id": "OA-3.1", "assertion": "Current epoch is validated, so an old attempt loses.", "obligation": "R2-c4"},
    {"id": "OA-3.2", "assertion": "A superseded Activation cannot be revived.", "obligation": "R2-e4"},
    {"id": "OA-3.3", "assertion": "Base progress revision is checked against pinned accepted progress.", "obligation": "R3-i1"},
    {"id": "OA-3.4", "assertion": "Cancellation fence is checked during acceptance.", "obligation": "R7-a1"},
    {"id": "OA-3.5", "assertion": "Same-Outcome Effect references resolve/bind during validation.", "obligation": "R3-g1"},
    {"id": "OA-3.6", "assertion": "A failure leaves no partial progress.", "obligation": "R3-c1"},
    {"id": "OA-3.7", "assertion": "A failure leaves no partial Effect intent.", "obligation": "R3-c3"},
    {"id": "OA-3.8", "assertion": "A failure leaves no partial acknowledgment.", "obligation": "R3-c2"},
  ] },
  { decision: "OA-4", rows: [3, 7], clauses: [
    {"id": "OA-4.1", "assertion": "Accepted Effect intents commit with the whole accepted set, before dispatch.", "obligation": "R3-g2"},
    {"id": "OA-4.2", "assertion": "Cancellation ordering prevents progress from a losing commit.", "obligation": "R7-a2"},
    {"id": "OA-4.3", "assertion": "Cancellation ordering prevents losing emissions.", "obligation": "R7-a3"},
    {"id": "OA-4.4", "assertion": "Cancellation ordering prevents losing acknowledgment.", "obligation": "R7-a4"},
    {"id": "OA-4.5", "assertion": "Cancellation ordering prevents losing intents.", "obligation": "R7-a5"},
    {"id": "OA-4.6", "assertion": "Cancellation ordering prevents losing next state.", "obligation": "R7-a6"},
    {"id": "OA-4.7", "assertion": "Cancellation ordering prevents losing wait.", "obligation": "R7-a6b"},
    {"id": "OA-4.8", "assertion": "Cancellation ordering prevents losing deadline.", "obligation": "R7-a6c"},
    {"id": "OA-4.9", "assertion": "Cancellation ordering prevents losing readiness.", "obligation": "R7-a6d"},
    {"id": "OA-4.10", "assertion": "Await commit follows W-2 acknowledgment-before-mailbox order.", "obligation": "R5-c1"},
    {"id": "OA-4.11", "assertion": "Await commit checks already accepted Events.", "obligation": "R5-c2"},
    {"id": "OA-4.12", "assertion": "Await commit collapses an already-due deadline.", "obligation": "R5-c3"},
    {"id": "OA-4.13", "assertion": "Otherwise await persists live deadline/registration together.", "obligation": "R5-c4"},
    {"id": "OA-4.14", "assertion": "These accepted facts survive a crash as one boundary, not partial durable writes.", "obligation": "R5-i1"},
  ] },
  { decision: "OA-5", rows: [3, 7], clauses: [
    {"id": "OA-5.1", "assertion": "Rejected envelope commits no progress.", "obligation": "R3-c1"},
    {"id": "OA-5.2", "assertion": "Rejected envelope accepts no emissions.", "obligation": "R3-c1b"},
    {"id": "OA-5.3", "assertion": "Rejected envelope acknowledges no Events.", "obligation": "R3-c2"},
    {"id": "OA-5.4", "assertion": "Rejected envelope creates no Effect intent.", "obligation": "R3-c3"},
    {"id": "OA-5.5", "assertion": "Rejected envelope accepts no deadline.", "obligation": "R3-c4"},
    {"id": "OA-5.6", "assertion": "Rejected envelope installs no wait.", "obligation": "R3-c5"},
    {"id": "OA-5.7", "assertion": "Rejected envelope creates no next-state transition.", "obligation": "R3-c6"},
    {"id": "OA-5.8", "assertion": "Rejected envelope creates no readiness.", "obligation": "R3-c7"},
    {"id": "OA-5.9", "assertion": "Rejection has an inspectable recorded reason rather than being dropped.", "obligation": "R3-b"},
    {"id": "OA-5.10", "assertion": "Kernel must not silently retry an unclassifiable protocol failure.", "obligation": "R3-h2"},
    {"id": "OA-5.11", "assertion": "Cancellation rejection exact replay cannot mutate its winner.", "obligation": "R7-b2"},
    {"id": "OA-5.12", "assertion": "A classified rejected Outcome is never automatically retried by the Kernel.", "obligation": "R3-i2"},
  ] },
  { decision: "OA-6", rows: [3], clauses: [
    {"id": "OA-6.1", "assertion": "Unclassifiable Runtime failure ends/holds under an explicit inspectable recovery decision.", "obligation": "R3-h1"},
    {"id": "OA-6.2", "assertion": "The failure cannot enter an infinite silent dispatch retry loop.", "obligation": "R3-h2"},
  ] },
  { decision: "EF-1", rows: [4], clauses: [
    {"id": "EF-1.1", "assertion": "K1 Effect-bearing Outcome is explicitly refused.", "obligation": "R4-a1"},
    {"id": "EF-1.2", "assertion": "The Effect is not stripped from an otherwise accepted Outcome.", "obligation": "R4-a3"},
    {"id": "EF-1.3", "assertion": "K1 refusal never dispatches external work.", "obligation": "R4-a4"},
  ] },
  { decision: "EF-2", rows: [4], clauses: [
    {"id": "EF-2.1", "assertion": "Refusal occurs at whole-envelope validation, not a visit to admission.", "obligation": "R4-a1"},
    {"id": "EF-2.2", "assertion": "Refusal creates no intent, Effect ID or proposal-key binding.", "obligation": "R4-a2"},
    {"id": "EF-2.3", "assertion": "The rest of the envelope is rejected too.", "obligation": "R4-a3"},
  ] },
  { decision: "EF-3", rows: [4], clauses: [
    {"id": "EF-3.1", "assertion": "Request disposition remains an independent dimension.", "obligation": "R4-c1"},
    {"id": "EF-3.2", "assertion": "Attempt evidence remains an independent dimension.", "obligation": "R4-c2"},
    {"id": "EF-3.3", "assertion": "Result validity/partial evidence remains an independent dimension.", "obligation": "R4-c3"},
    {"id": "EF-3.4", "assertion": "Responsibility remains an independent dimension.", "obligation": "R4-c4"},
    {"id": "EF-3.5", "assertion": "K1 itself instantiates none of those action facts because no intent exists.", "obligation": "R4-a2"},
  ] },
  { decision: "EF-4", rows: [4], clauses: [
    {"id": "EF-4.1", "assertion": "Denial without attempt is not evidence of external failure.", "obligation": "R4-d1"},
    {"id": "EF-4.2", "assertion": "Waiting for consent consumes no attempt.", "obligation": "R4-d2"},
    {"id": "EF-4.3", "assertion": "Unconfirmed admitted work is unknown.", "obligation": "R4-d3"},
    {"id": "EF-4.4", "assertion": "Acknowledging unknown does not discharge completion responsibility.", "obligation": "R4-d4"},
    {"id": "EF-4.5", "assertion": "Stopping retry is not proof of external failure.", "obligation": "R4-d5"},
    {"id": "EF-4.6", "assertion": "Unsupported K1 content creates no denied/unknown action record.", "obligation": "R4-a2"},
    {"id": "EF-4.7", "assertion": "The entire unsupported K1 envelope is refused.", "obligation": "R4-a3"},
  ] },
  { decision: "CX-1", rows: [7], clauses: [
    {"id": "CX-1.1", "assertion": "Cancellation is an out-of-band control accepted independently of Runtime cooperation or batch.", "obligation": "R7-c1"},
    {"id": "CX-1.2", "assertion": "Acceptance immediately fences later Runtime progress.", "obligation": "R7-a2"},
    {"id": "CX-1.3", "assertion": "Acceptance immediately blocks new Effect admission.", "obligation": "R7-e1"},
    {"id": "CX-1.4", "assertion": "Driver cancellation is requested independently; physical interruption may be later.", "obligation": "R7-e2"},
  ] },
  { decision: "CX-2", rows: [7], clauses: [
    {"id": "CX-2.1", "assertion": "Cancellation acceptance first makes the later Outcome lose, independently of submission time/physical interruption.", "obligation": "R7-a1"},
    {"id": "CX-2.2", "assertion": "Outcome acceptance first: terminal completion/failure is never reopened by later cancel.", "obligation": "R7-d"},
    {"id": "CX-2.3", "assertion": "Cancellation of a nonterminal state applies to that resulting state.", "obligation": "R7-c1"},
    {"id": "CX-2.4", "assertion": "Only suppressing next state while accepting losing progress is not atomic ordering.", "obligation": "R7-a8"},
  ] },
  { decision: "CX-3", rows: [8], clauses: [
    {"id": "CX-3.1", "assertion": "Completing Outcome proposing new Effects is refused at acceptance, never a later cleanup pass.", "obligation": "R8-a"},
    {"id": "CX-3.2", "assertion": "Previously required Effect work must be accounted for.", "obligation": "R8-c"},
    {"id": "CX-3.3", "assertion": "Previously required child work must be accounted for under policy.", "obligation": "R8-d"},
    {"id": "CX-3.4", "assertion": "A refused completing envelope has an inspectable recorded reason.", "obligation": "R8-a2"},
    {"id": "CX-3.5", "assertion": "A refused completing envelope installs no progress.", "obligation": "R8-a3"},
    {"id": "CX-3.6", "assertion": "A refused completing envelope acknowledges no batch.", "obligation": "R8-a4"},
    {"id": "CX-3.7", "assertion": "A refused completing envelope creates no intent or key binding.", "obligation": "R8-a5"},
  ] },
  { decision: "CX-4", rows: [8], clauses: [
    {"id": "CX-4.1", "assertion": "Unknown required work bars completion.", "obligation": "R8-e1"},
    {"id": "CX-4.2", "assertion": "Unknown required work does not bar cancellation.", "obligation": "R8-e2"},
    {"id": "CX-4.3", "assertion": "Cancellation retains unknown evidence for reconciliation without claiming resolution.", "obligation": "R8-e3"},
  ] },
  { decision: "CX-5", rows: [7], clauses: [
    {"id": "CX-5.1", "assertion": "Late authenticated settlement retains original attempt/Effect identity.", "obligation": "R7-f1"},
    {"id": "CX-5.2", "assertion": "Late settlement never reopens the cancelled Execution.", "obligation": "R7-f2"},
    {"id": "CX-5.3", "assertion": "Late settlement never becomes a new unrelated Effect.", "obligation": "R7-f3"},
  ] },
  { decision: "CX-6", rows: [7, 8], clauses: [
    {"id": "CX-6.1", "assertion": "Authentication precedes cancellation-rejection lookup.", "obligation": "R3-e1"},
    {"id": "CX-6.2", "assertion": "Lookup is access-scoped.", "obligation": "R3-e2"},
    {"id": "CX-6.3", "assertion": "Losing envelope gets the recorded cancellation/terminal-conflict reason bound to identity/content.", "obligation": "R7-a1"},
    {"id": "CX-6.4", "assertion": "Losing envelope installs no progress/revision.", "obligation": "R7-a2"},
    {"id": "CX-6.5", "assertion": "Losing envelope accepts no emissions.", "obligation": "R7-a3"},
    {"id": "CX-6.6", "assertion": "Losing envelope acknowledges no reserved Events.", "obligation": "R7-a4"},
    {"id": "CX-6.7", "assertion": "Losing envelope installs no intents.", "obligation": "R7-a5"},
    {"id": "CX-6.8", "assertion": "Losing envelope installs no next state.", "obligation": "R7-a6"},
    {"id": "CX-6.9", "assertion": "Losing await installs no wait.", "obligation": "R7-a6b"},
    {"id": "CX-6.10", "assertion": "Losing await installs no deadline.", "obligation": "R7-a6c"},
    {"id": "CX-6.11", "assertion": "Losing await installs no readiness.", "obligation": "R7-a6d"},
    {"id": "CX-6.12", "assertion": "A complete loser is fenced just as continue/await are.", "obligation": "R7-a7"},
    {"id": "CX-6.13", "assertion": "Control path reaches CANCELLED without waiting for the loser.", "obligation": "R7-c1"},
    {"id": "CX-6.14", "assertion": "Reserved unacknowledged Events receive terminal disposition.", "obligation": "R7-c2"},
    {"id": "CX-6.15", "assertion": "Terminal after wait retirement before reservation suppresses that Activation and disposes the timeout.", "obligation": "R5-k7"},
    {"id": "CX-6.16", "assertion": "Exact rejected identity/content retry returns the same recorded rejection.", "obligation": "R7-b2"},
    {"id": "CX-6.17", "assertion": "Rejected replay mints no acceptance receipt.", "obligation": "R7-b"},
    {"id": "CX-6.18", "assertion": "Recovery/retention preserves fence and rejection; expiration cannot admit the loser.", "obligation": "R7-g1"},
    {"id": "CX-6.19", "assertion": "Previously accepted receipt replay remains accepted after subsequent cancellation.", "obligation": "R7-g2"},
  ] },
  { decision: "PC-1", rows: [9], clauses: [
    {"id": "PC-1.1", "assertion": "Inline progress is stored/returned unchanged.", "obligation": "R9-b1"},
    {"id": "PC-1.2", "assertion": "Immutable checkpoint and still-running native job references retain distinct recovery guarantees.", "obligation": "R9-b2"},
    {"id": "PC-1.3", "assertion": "Compatibility comes from pinned definition/Runtime/codec, never a legacy Agent/Workflow tag.", "obligation": "R9-b3"},
  ] },
  { decision: "PC-2", rows: [9], clauses: [
    {"id": "PC-2.1", "assertion": "Publish immutable checkpoint before proposing its reference.", "obligation": "R9-c1"},
    {"id": "PC-2.2", "assertion": "Acceptance pins the checkpoint.", "obligation": "R9-c2"},
    {"id": "PC-2.3", "assertion": "Rejection does not pin it.", "obligation": "R9-c3"},
    {"id": "PC-2.4", "assertion": "Checkpoint identity carries codec/version and required resource versions.", "obligation": "R9-c4"},
  ] },
  { decision: "PC-3", rows: [9], clauses: [
    {"id": "PC-3.1", "assertion": "Mutable session locator is not a checkpoint and Kernel CAS cannot prevent its native mutation.", "obligation": "R9-d1"},
    {"id": "PC-3.2", "assertion": "Locator recovery requires explicit Driver exclusive-ownership/reconciliation declaration.", "obligation": "R9-d2"},
    {"id": "PC-3.3", "assertion": "Without that declaration automatic locator takeover is refused.", "obligation": "R9-d3"},
  ] },
  { decision: "PC-4", rows: [9], clauses: [
    {"id": "PC-4.1", "assertion": "Persisted progress is versioned to the exact compatible Runtime/definition revision.", "obligation": "R9-e"},
    {"id": "PC-4.2", "assertion": "Unavailable pinned code produces explicit inspectable hold/refusal.", "obligation": "R9-a1"},
    {"id": "PC-4.3", "assertion": "Missing compatible code never causes a fresh start presented as restoration.", "obligation": "R9-a2"},
  ] },
  { decision: "PC-5", rows: [9], clauses: [
    {"id": "PC-5.1", "assertion": "Missing compatible-code recovery produces an inspectable hold/refusal.", "obligation": "R9-a1"},
    {"id": "PC-5.2", "assertion": "Missing compatible-code recovery never fabricates empty restored progress.", "obligation": "R9-a2"},
    {"id": "PC-5.3", "assertion": "Missing checkpoint recovery is explicitly held, never fabricated.", "obligation": "R9-f1"},
    {"id": "PC-5.4", "assertion": "Missing required-resource recovery is explicitly held, never fabricated.", "obligation": "R9-f2"},
  ] },
  { decision: "LP-1", rows: [10], clauses: [
    {"id": "LP-1.1", "assertion": "Local acceptance checks read the just-accepted state with no staleness window.", "obligation": "R10-a"},
  ] },
  { decision: "LP-2", rows: [10], clauses: [
    {"id": "LP-2.1", "assertion": "No K0/K1 promise treats a synchronous-looking remote check as a remote-revocation freshness guarantee.", "obligation": "R10-b"},
  ] },
  { decision: "LP-3", rows: [10], clauses: [
    {"id": "LP-3.1", "assertion": "Ordinary corrective input cannot retract an accepted Outcome.", "obligation": "R10-c"},
    {"id": "LP-3.2", "assertion": "Ordinary corrective input cannot withdraw an accepted Effect intent.", "obligation": "R10-d1"},
    {"id": "LP-3.3", "assertion": "Ordinary corrective input cannot invalidate an admission; explicit withdrawal is separate.", "obligation": "R10-d2"},
  ] },
];
