/**
 * Round-15 authored independence judgments. These are review inputs, not inferred semantics.
 * Each group records why its prior owner bundled separable facts, the resulting owners, and
 * every source-clause binding to those owners. The guard rejects re-bundling even if the general
 * inventory seal is recomputed. Changing these judgments requires reviewing the stated bug model.
 */
export const CLAUSE_REFINEMENTS: readonly {
  readonly priorOwner: string;
  readonly reason: string;
  readonly owners: readonly string[];
  readonly clauses: readonly { readonly id: string; readonly obligation: string }[];
}[] = [
  {"priorOwner": "R5-j1", "reason": "A schedule can use bound zero without forging an Event, or forge an Event under a positive bound.", "owners": ["R5-j1", "R5-j1-2"], "clauses": [{"id": "B-1.1-r5-j1", "obligation": "R5-j1"}, {"id": "B-1.4-r5-j1", "obligation": "R5-j1"}, {"id": "B-1.5", "obligation": "R5-j1"}, {"id": "B-1.5-2", "obligation": "R5-j1-2"}, {"id": "W-9.1-r5-j1", "obligation": "R5-j1"}]},
  {"priorOwner": "R5-k6", "reason": "The minting writer can compute each envelope field incorrectly while the other three are correct. Supplied laboratory Event identity retention (R5-f2a) is not Kernel identity minting.", "owners": ["R5-k6", "R5-k6-2", "R5-k6-3", "R5-k6-4"], "clauses": [{"id": "W-9.2", "obligation": "R5-k6"}, {"id": "W-9.2-2", "obligation": "R5-k6-2"}, {"id": "W-9.2-3", "obligation": "R5-k6-3"}, {"id": "W-9.2-4", "obligation": "R5-k6-4"}]},
  {"priorOwner": "R2-e1", "reason": "Input serialization can drift independently of the dispatched base-revision field.", "owners": ["R2-e1", "R2-e1-2"], "clauses": [{"id": "ID-3.3", "obligation": "R2-e1"}, {"id": "ID-3.3-2", "obligation": "R2-e1-2"}]},
  {"priorOwner": "R2-e2", "reason": "Authentication, recovery permission, epoch-as-credential and liveness-as-authority are separate admission predicates.", "owners": ["R2-e2", "R2-e2-2", "R2-e2-3", "R2-e2-4"], "clauses": [{"id": "ID-3.10", "obligation": "R2-e2"}, {"id": "ID-3.10-2", "obligation": "R2-e2-2"}, {"id": "ID-3.10-3", "obligation": "R2-e2-3"}, {"id": "ID-3.10-4", "obligation": "R2-e2-4"}]},
  {"priorOwner": "R5-h1", "reason": "Three roles permit pairwise conflation: distinguishing wait/Execution does not prove either is distinct from lease.", "owners": ["R5-h1", "R5-h1-2", "R5-h1-3"], "clauses": [{"id": "CL-1.1", "obligation": "R5-h1"}, {"id": "CL-1.1-2", "obligation": "R5-h1-2"}, {"id": "CL-1.1-3", "obligation": "R5-h1-3"}]},
  {"priorOwner": "R5-h2", "reason": "The expiry-to-control mapper can work while its consumer falsely reports physical interruption.", "owners": ["R5-h2", "R5-h2-2"], "clauses": [{"id": "CL-1.2", "obligation": "R5-h2"}, {"id": "CL-1.2-2", "obligation": "R5-h2-2"}]},
  {"priorOwner": "R5-h3", "reason": "Recovery scheduling, death inference and authority admission can fail independently.", "owners": ["R5-h3", "R5-h3-2", "R5-h3-3"], "clauses": [{"id": "ID-9.7", "obligation": "R5-h3"}, {"id": "ID-9.7-2", "obligation": "R5-h3-2"}, {"id": "ID-9.7-3", "obligation": "R5-h3-3"}, {"id": "CL-1.3", "obligation": "R5-h3"}, {"id": "CL-1.3-2", "obligation": "R5-h3-2"}, {"id": "CL-1.3-3", "obligation": "R5-h3-3"}]},
  {"priorOwner": "R5-h4", "reason": "A consumer may classify failed execution without asserting non-execution, or assert the latter independently.", "owners": ["R5-h4", "R5-h4-2"], "clauses": [{"id": "B-7.10", "obligation": "R5-h4"}, {"id": "B-7.10-2", "obligation": "R5-h4-2"}, {"id": "CL-2.2", "obligation": "R5-h4"}, {"id": "CL-2.2-2", "obligation": "R5-h4-2"}, {"id": "W-9.9", "obligation": "R5-h4"}, {"id": "W-9.9-2", "obligation": "R5-h4-2"}]},
  {"priorOwner": "R5-i4", "reason": "Source replay deduplication and destination readiness are different writers.", "owners": ["R5-i4", "R5-i4-2"], "clauses": [{"id": "B-6.9", "obligation": "R5-i4"}, {"id": "B-6.9-2", "obligation": "R5-i4-2"}]},
  {"priorOwner": "R5-i5", "reason": "Correct destination wake ownership does not authorize rejecting a conforming single-transaction implementation.", "owners": ["R5-i5", "R5-i5-2"], "clauses": [{"id": "B-6.10", "obligation": "R5-i5"}, {"id": "B-6.10-2", "obligation": "R5-i5-2"}]},
  {"priorOwner": "R7-f1", "reason": "The Effect association and physical attempt association can each be rebound independently.", "owners": ["R7-f1", "R7-f1-2"], "clauses": [{"id": "CX-5.1", "obligation": "R7-f1"}, {"id": "CX-5.1-2", "obligation": "R7-f1-2"}]},
  {"priorOwner": "R7-g1", "reason": "Fence persistence, rejection persistence and expiration policy are separate operations; first ownership follows those operations.", "owners": ["R7-g1", "R7-g1-2", "R7-g1-3"], "clauses": [{"id": "CX-6.18", "obligation": "R7-g1"}, {"id": "CX-6.18-2", "obligation": "R7-g1-2"}, {"id": "CX-6.18-3", "obligation": "R7-g1-3"}]},
  {"priorOwner": "R8-e3", "reason": "A cancellation writer can retain a record but relabel its certainty, or delete it without asserting certainty.", "owners": ["R8-e3", "R8-e3-2"], "clauses": [{"id": "CX-4.3", "obligation": "R8-e3"}, {"id": "CX-4.3-2", "obligation": "R8-e3-2"}]},
  {"priorOwner": "R9-b1", "reason": "Persistence and outbound payload serialization can differ independently.", "owners": ["R9-b1", "R9-b1-2"], "clauses": [{"id": "PC-1.1", "obligation": "R9-b1"}, {"id": "PC-1.1-2", "obligation": "R9-b1-2"}]},
  {"priorOwner": "R9-b3", "reason": "Each compatibility lookup dimension can be omitted or substituted independently.", "owners": ["R9-b3", "R9-b3-2", "R9-b3-3", "R9-b3-4"], "clauses": [{"id": "PC-1.3", "obligation": "R9-b3"}, {"id": "PC-1.3-2", "obligation": "R9-b3-2"}, {"id": "PC-1.3-3", "obligation": "R9-b3-3"}, {"id": "PC-1.3-4", "obligation": "R9-b3-4"}]},
  {"priorOwner": "R9-c4", "reason": "Reference metadata serializers can omit codec, version or resources independently.", "owners": ["R9-c4", "R9-c4-2", "R9-c4-3"], "clauses": [{"id": "PC-2.4", "obligation": "R9-c4"}, {"id": "PC-2.4-2", "obligation": "R9-c4-2"}, {"id": "PC-2.4-3", "obligation": "R9-c4-3"}]},
  {"priorOwner": "R9-d1", "reason": "Form classification and external-fencing capability claims are separate Driver declarations.", "owners": ["R9-d1", "R9-d1-2"], "clauses": [{"id": "PC-3.1", "obligation": "R9-d1"}, {"id": "PC-3.1-2", "obligation": "R9-d1-2"}]},
  {"priorOwner": "R9-e", "reason": "Runtime and definition loaders can each choose the wrong revision while the other is pinned correctly.", "owners": ["R9-e", "R9-e-2"], "clauses": [{"id": "PC-4.1", "obligation": "R9-e"}, {"id": "PC-4.1-2", "obligation": "R9-e-2"}]},
  {"priorOwner": "R9-f1", "reason": "A silent stop and a fabricated fresh start are different failure constructions, just as R9-a1/a2 already distinguish missing code.", "owners": ["R9-f1", "R9-f1-2"], "clauses": [{"id": "PC-5.3", "obligation": "R9-f1"}, {"id": "PC-5.3-2", "obligation": "R9-f1-2"}]},
  {"priorOwner": "R9-f2", "reason": "A silent stop and a fabricated fresh start are different failure constructions, just as R9-a1/a2 already distinguish missing code.", "owners": ["R9-f2", "R9-f2-2"], "clauses": [{"id": "PC-5.4", "obligation": "R9-f2"}, {"id": "PC-5.4-2", "obligation": "R9-f2-2"}]},
  {"priorOwner": "R5-j8", "reason": "Lifecycle/generation equivalence, readiness lifecycle and readiness provenance have independently writable observations.", "owners": ["R5-j8", "R5-j8-2", "R5-j8-3"], "clauses": [{"id": "B-8.4-2", "obligation": "R5-j8-2"}, {"id": "B-8.4-3", "obligation": "R5-j8-3"}, {"id": "W-3.7", "obligation": "R5-j8"}]},
  {"priorOwner": "R5-j9", "reason": "A reservation may clear readiness correctly and a later writer may resurrect it.", "owners": ["R5-j9", "R5-j9-2"], "clauses": [{"id": "B-8.5", "obligation": "R5-j9"}, {"id": "B-8.5-2", "obligation": "R5-j9-2"}, {"id": "W-8.10", "obligation": "R5-j9"}, {"id": "W-8.10-2", "obligation": "R5-j9-2"}]},
  {"priorOwner": "R5-k3", "reason": "Adding a callback does not imply adding interleave or native-work state; a shared closed-shape test does not unify the claims.", "owners": ["R5-k3", "R5-k3-2", "R5-k3-3", "R5-k3-4", "R5-k3-5"], "clauses": [{"id": "W-1.17", "obligation": "R5-k3"}, {"id": "W-1.17-2", "obligation": "R5-k3-2"}, {"id": "W-1.17-3", "obligation": "R5-k3-3"}, {"id": "W-1.17-4", "obligation": "R5-k3-4"}, {"id": "W-1.17-5", "obligation": "R5-k3-5"}, {"id": "W-4.3-4", "obligation": "R5-k3-4"}, {"id": "W-4.3-5", "obligation": "R5-k3-5"}, {"id": "W-5.1-3", "obligation": "R5-k3-3"}]},
  {"priorOwner": "R2-e3", "reason": "An oracle can allow resets yet require numeric spelling, or allow opaque tokens while incorrectly requiring global order.", "owners": ["R2-e3", "R2-e3-2"], "clauses": [{"id": "ID-4.4", "obligation": "R2-e3"}, {"id": "ID-4.4-2", "obligation": "R2-e3-2"}]},
  {"priorOwner": "R1-g", "reason": "Boundary namespace and within-boundary position are separate receipt coordinates.", "owners": ["R1-g", "R1-g-2"], "clauses": [{"id": "ID-6.6", "obligation": "R1-g"}, {"id": "ID-6.6-2", "obligation": "R1-g-2"}, {"id": "ID-7.2", "obligation": "R1-g"}, {"id": "ID-7.2-2", "obligation": "R1-g-2"}]},
  {"priorOwner": "R5-i1", "reason": "Outcome and Event acceptance are separate durable writers, with distinct Event/deadline paths; surviving readiness is not surviving mailbox data.", "owners": ["R5-i1", "R5-i1-2", "R5-i1-3", "R5-i1-4", "R5-i1-5", "R5-i1-6"], "clauses": [{"id": "B-2.6", "obligation": "R5-i1"}, {"id": "B-2.6-2", "obligation": "R5-i1-2"}, {"id": "B-2.6-3", "obligation": "R5-i1-3"}, {"id": "B-2.6-4", "obligation": "R5-i1-4"}, {"id": "B-2.6-5", "obligation": "R5-i1-5"}, {"id": "B-6.11", "obligation": "R5-i1"}, {"id": "B-6.11-2", "obligation": "R5-i1-2"}, {"id": "B-7.11-3", "obligation": "R5-i1-3"}, {"id": "B-7.11-4", "obligation": "R5-i1-4"}, {"id": "B-7.11-6", "obligation": "R5-i1-6"}, {"id": "B-8.8", "obligation": "R5-i1"}, {"id": "B-8.8-2", "obligation": "R5-i1-2"}, {"id": "B-8.8-3", "obligation": "R5-i1-3"}, {"id": "B-8.8-4", "obligation": "R5-i1-4"}, {"id": "W-2.14", "obligation": "R5-i1"}, {"id": "W-2.14-3", "obligation": "R5-i1-3"}, {"id": "OA-4.14", "obligation": "R5-i1"}, {"id": "OA-4.14-3", "obligation": "R5-i1-3"}]},
  {"priorOwner": "R4-b1", "reason": "Receipt boundary and position are independently encoded coordinates, as at dispatch; neither coordinate proves subsequent work succeeded.", "owners": ["R4-b1", "R4-b1-2"], "clauses": [{"id": "ID-6.14", "obligation": "R4-b1"}, {"id": "ID-6.14-2", "obligation": "R4-b1-2"}, {"id": "ID-7.4", "obligation": "R4-b1"}, {"id": "ID-7.4-2", "obligation": "R4-b1-2"}]},
  {"priorOwner": "R4-b2", "reason": "Receipt boundary and position are independently encoded coordinates, as at dispatch; neither coordinate proves subsequent work succeeded.", "owners": ["R4-b2", "R4-b2-2"], "clauses": [{"id": "ID-6.15", "obligation": "R4-b2"}, {"id": "ID-6.15-2", "obligation": "R4-b2-2"}, {"id": "ID-7.5", "obligation": "R4-b2"}, {"id": "ID-7.5-2", "obligation": "R4-b2-2"}]},
  {"priorOwner": "R4-b3", "reason": "Receipt boundary and position are independently encoded coordinates, as at dispatch; neither coordinate proves subsequent work succeeded.", "owners": ["R4-b3", "R4-b3-2"], "clauses": [{"id": "ID-6.16", "obligation": "R4-b3"}, {"id": "ID-6.16-2", "obligation": "R4-b3-2"}, {"id": "ID-7.6", "obligation": "R4-b3"}, {"id": "ID-7.6-2", "obligation": "R4-b3-2"}]},
  {"priorOwner": "R4-b4", "reason": "Receipt boundary and position are independently encoded coordinates, as at dispatch; neither coordinate proves subsequent work succeeded.", "owners": ["R4-b4", "R4-b4-2"], "clauses": [{"id": "ID-6.17", "obligation": "R4-b4"}, {"id": "ID-6.17-2", "obligation": "R4-b4-2"}, {"id": "ID-7.7", "obligation": "R4-b4"}, {"id": "ID-7.7-2", "obligation": "R4-b4-2"}]},
  {"priorOwner": "R5-j6", "reason": "An implementation can omit an obedience field but still parse progress internally; a field-shape scan proves only the former.", "owners": ["R5-j6", "R5-j6-2"], "clauses": [{"id": "B-3.5", "obligation": "R5-j6"}, {"id": "B-3.5-2", "obligation": "R5-j6-2"}]},
  {"priorOwner": "R9-c1", "reason": "Publication order and post-publication mutability are independently controlled by the Driver and resource store.", "owners": ["R9-c1", "R9-c1-2"], "clauses": [{"id": "PC-2.1", "obligation": "R9-c1"}, {"id": "PC-2.1-2", "obligation": "R9-c1-2"}]},
  {"priorOwner": "R5-k5", "reason": "The bridge can encapsulate resumptions correctly while dropping interleave behavior, or leak resumptions while preserving that behavior.", "owners": ["R5-k5", "R5-k5-2"], "clauses": [{"id": "W-4.4", "obligation": "R5-k5"}, {"id": "W-5.3-2", "obligation": "R5-k5-2"}]},
  {"priorOwner": "R5-d1", "reason": "Round-16 self-audit of the B-2 neighbourhood: readiness is a record with a species and a retired generation, not a flag, and it is the input to B-2's choice between the wait-ended rule and acceptance-order selection. A path-B handler can retire the registration perfectly and still mark the Execution plainly READY, which is a coherent §3 row 5 state.", "owners": ["R5-d1", "R5-d1b"], "clauses": [{"id": "B-6.4", "obligation": "R5-d1"}, {"id": "B-6.4-2", "obligation": "R5-d1b"}]},
  {"priorOwner": "R5-e1", "reason": "Round-16 K02-R16-01: retaining the mandatory member, choosing the earliest-accepted eligible one when the bound truncates, and treating ineligible Events as candidates for nothing are three writers. At bound one with a single candidate they produce one observation; with room to spare a selector can keep the right member and still top the batch up from the whole mailbox.", "owners": ["R5-e1", "R5-e1b", "R5-e1c"], "clauses": [{"id": "B-2.2", "obligation": "R5-e1"}, {"id": "B-2.2-r5-e1b", "obligation": "R5-e1b"}, {"id": "B-2.2-r5-e1c", "obligation": "R5-e1c"}, {"id": "B-4.4", "obligation": "R5-e1c"}, {"id": "B-6.6", "obligation": "R5-e1"}, {"id": "W-7.8", "obligation": "R5-e1c"}, {"id": "W-8.9", "obligation": "R5-e1"}]},
  {"priorOwner": "R5-e2", "reason": "Round-16 K02-R16-01: the deadline species' mandatory member is Kernel-minted at expiry, so it is younger than the backlog beside it and a top-up in acceptance order presents the ineligible Event first. Displacement at bound one and candidacy with room are separate branches, and the genus-level exclusion clause is split by species rather than assumed to share code.", "owners": ["R5-e2", "R5-e2b"], "clauses": [{"id": "B-1.4", "obligation": "R5-e2"}, {"id": "B-2.3", "obligation": "R5-e2"}, {"id": "B-2.3-r5-e2b", "obligation": "R5-e2b"}, {"id": "B-4.4-2", "obligation": "R5-e2b"}, {"id": "B-7.7", "obligation": "R5-e2"}, {"id": "W-8.14", "obligation": "R5-e2"}, {"id": "W-9.1", "obligation": "R5-e2"}, {"id": "W-9.10", "obligation": "R5-e2"}]},
  {"priorOwner": "R5-i6", "reason": "Trust verification and the two independently exposed submitting-principal paths can each admit a forgery without the other doing so.", "owners": ["R5-i6", "R5-i6-2", "R5-i6-3"], "clauses": [{"id": "W-9.3", "obligation": "R5-i6"}, {"id": "W-9.3-2", "obligation": "R5-i6-2"}, {"id": "W-9.3-3", "obligation": "R5-i6-3"}]},
];
