#!/usr/bin/env python3
"""DA-1: pinned review discovery, ID occurrences, curated classification, and families."""
from pathlib import Path
import collections, hashlib, json, re, subprocess, sys
HERE=Path(__file__).resolve().parent
ROOT=HERE.parents[3]
B='66bc041175e6fc191c2e7cf88de198111e7d97c9'
A='9fd2faa71bc4e2b7b4798c53a0360b669c5d7b49'
RX=re.compile(r'(?<![\w.-])(?:K(?:01|02|10|11|12(?:C1)?)-(?:[A-Z0-9]+-)+\d{2}|KC[12]-(?:[A-Z0-9]+-)+\d{2}|REF1-(?:[A-Z0-9]+-)+\d{2}|K[01]\.[02]-SELF-\d{2}|CORR2-SELF-\d{2}|SELF-(?:[A-Z0-9]+-)*\d{2}|O-R\d+-\d+)(?![\w-])')
def git(*args):return subprocess.check_output(['git','-C',str(ROOT),*args]).decode()
def sources():
 out=[]
 for rev in [A,B]:
  for p in git('ls-tree','-r','--name-only',rev,'docs/development/work').splitlines():
   packet=p.split('/')[3]
   allowed=bool(re.fullmatch(r'K(?:0\.[12]|1\.[01])(?:-(?:correction|reference)-\d+)?',packet)) if rev==A else packet in ['K1.1-correction-02','K1.2','K1.2-correction-01']
   if allowed and p.endswith('.md') and any(x.startswith(('review','cleanup','handoff','owner-note')) for x in p.split('/')[4:]):
    out.append(dict(rev=rev,path=p,text=git('show',rev+':'+p)))
 return out

def extract(ss):
 occ=collections.defaultdict(list)
 for s in ss:
  for n,line in enumerate(s['text'].splitlines(),1):
   for m in RX.finditer(line):
    k=m.group()
    # SELF and observation labels are local namespaces, never global IDs.
    if k.startswith(('SELF-','O-','CORR2-')):k=s['path'].split('/')[3]+'::'+k
    occ[k].append(dict(rev=s['rev'],path=s['path'],line=n,text=line))
    tail=line[m.end():]
    if m.group()=='SELF-DIAG-01' and tail.startswith('/02'):
     occ[s['path'].split('/')[3]+'::SELF-DIAG-02'].append(dict(rev=s['rev'],path=s['path'],line=n,text=line))
    if m.group()=='SELF-R6-HOST-01' and tail.startswith('–03'):
     for end in ['02','03']:occ[s['path'].split('/')[3]+'::SELF-R6-HOST-'+end].append(dict(rev=s['rev'],path=s['path'],line=n,text=line))
   if 'CATALOG-01' in line and s['path'].split('/')[3]=='K1.2-correction-01':
    occ['K1.2-correction-01::CATALOG-01'].append(dict(rev=s['rev'],path=s['path'],line=n,text=line))
   # Some reviews label observations O1/O2 rather than O-Rn-1. Preserve locality.
   m=re.match(r'^\s*[-*]\s+\*\*(O\d+)\b',line)
   if m:
    k=s['path']+'::'+m[1]
    occ[k].append(dict(rev=s['rev'],path=s['path'],line=n,text=line))
 return dict(sorted(occ.items()))

def render(ss,occ,mapping):
 assert set(occ)==set(mapping), {'unclassified':sorted(set(occ)-set(mapping)),'unused':sorted(set(mapping)-set(occ))}
 rows=[]; families=collections.defaultdict(list)
 for k,v in mapping.items():
  assert v['category'] in ['design','evidence','records']
  chosen=[o for o in occ[k] if o['path']==v['source'] and o['line']==v['line']]
  assert chosen,(k,v)
  if v['kind']!='alias':families[v['family']].append((k,v))
  rows.append([k,v['kind'],v['category'],v['subsystem'],v['family'],v.get('alias_of',''),v['summary'],f"[{v['source'].split('/work/')[1]}:{v['line']}](https://github.com/ArrokothI/arrokothi/blob/{chosen[0]['rev']}/{v['source']}#L{v['line']})"])
 summary={f:{'ids':len(v),'rounds':len(set(x['round'] for k,x in v if x['kind'] in ['finding','owner-supplement','cleanup'])), 'review_findings':sum(x['kind'] in ['finding','owner-supplement','cleanup'] for k,x in v), 'qualifies':sum(x['kind'] in ['finding','owner-supplement','cleanup'] for k,x in v)>=3 or len(set(x['round'] for k,x in v if x['kind'] in ['finding','owner-supplement','cleanup']))>=2} for f,v in sorted(families.items())}
 # Supplemental/self/observation labels are all retained; primary review counts remain separable.
 stats={'source_records':len(ss),'id_labels':len(mapping),'unique_non_alias_items':sum(v['kind']!='alias' for v in mapping.values()),'by_kind':dict(collections.Counter(v['kind'] for v in mapping.values())),'by_category_non_alias':dict(collections.Counter(v['category'] for v in mapping.values() if v['kind']!='alias')),'families':summary}
 md=['# DA-1 finding enumeration','',f'Archive `{A}`; active records `{B}`. Generated by `python3 enumerate.py`; classifications are explicit in `classifications.json`.','',
 'All full IDs matching the script grammar in the discovered review/cleanup/handoff/owner-note Markdown are retained, including references to implementer findings. Generic O labels are source-local. Aliases are listed and excluded from family totals. An occurrence is not a new finding. The definition or first explicit reference and origin round are curated, because historical filenames and ID round numbers sometimes disagree. Observations and referenced self-findings expand coverage and are distinguished by kind. Normative criteria/decision IDs and mutant names are not findings. `enumeration-occurrences.json` retains every matched occurrence; `review-sources.json` inventories every searched file, including no-finding records.','',
 'Family qualification counts review/owner/cleanup findings and their distinct origin rounds of findings/owner supplements/cleanup findings; later mentions do not add rounds. The register also covers all required starting items regardless of counts. See `enumeration-notes.md` for shorthand reconciliation and search limits.','',
 '| ID | Provenance kind | Category | Subsystem | Family | Alias of | Meaning | Definition or explicit reference |','|---|---|---|---|---|---|---|---|']
 md += ['| '+' | '.join(str(x).replace('|','\\|').replace('\n',' ') for x in row)+' |' for row in rows]
 md+=['','## Family selection','', '| Family | Items | Review findings | Origin rounds | Qualifies |','|---|---:|---:|---:|---|']
 md += [f"| {f} | {v['ids']} | {v['review_findings']} | {v['rounds']} | {v['qualifies']} |" for f,v in summary.items()]
 return {'da-1-table.md':'\n'.join(md)+'\n','enumeration-summary.json':json.dumps(stats,indent=2)+'\n','enumeration-occurrences.json':json.dumps(occ,indent=2)+'\n','review-sources.json':json.dumps([{k:v for k,v in s.items() if k!='text'}|{'sha256':hashlib.sha256(s['text'].encode()).hexdigest(),'lines':len(s['text'].splitlines())} for s in ss],indent=2)+'\n'}
if __name__=='__main__':
 ss=sources();occ=extract(ss)
 if '--discover' in sys.argv:
  (HERE/'enumeration-discovery.json').write_text(json.dumps(occ,indent=2)+'\n');print('Discovered',len(ss),'records and',len(occ),'labels');sys.exit()
 mapping=json.loads((HERE/'classifications.json').read_text())
 outputs=render(ss,occ,mapping)
 for name,data in outputs.items():
  if '--check' in sys.argv:assert (HERE/name).read_text()==data,name
  else:(HERE/name).write_text(data)
 print(outputs['enumeration-summary.json'])
