#!/usr/bin/env python3
"""Verify curated same-H reversals against pinned records and render review checklist."""
from pathlib import Path
import json,subprocess,sys
P=Path(__file__).resolve().parents[1]; R=P.parents[3]
rows=json.loads((P/'verdict-flips.json').read_text())
md=['# Verdict reversals and search checklist','', 'This is a declared search of the DA-1 review, handoff, supplement and cleanup records, including explicit disclosures of unrecorded draft ACCEPTs. An earlier search dimension is inferred from the later counterexample and earlier coverage record, not from access to a reviewer’s private reasoning. Cleanup reopenings are separately labelled: they are not fabricated independent CHANGES REQUIRED verdicts. Two later reviews against the same accepted H remain separate evidence rows; unique-head totals deduplicate them.','', '| Kind | Packet / exact H | Earlier → later record | Dimension not varied / checklist action |','|---|---|---|---|']
for r in rows:
 for key in ['earlier','later']:
  if r[key]:
   t=subprocess.check_output(['git','-C',str(R),'show',r['revision']+':'+r[key]]).decode();assert r['H'] in t,(r[key],r['H'])
 link=lambda p:f'[{p.split("/work/")[1]}](https://github.com/ArrokothI/arrokothi/blob/{r["revision"]}/{p})' if p else 'Unrecorded draft, disclosed by later record'
 md.append(f"| {r['kind']} | {r['packet']} / `{r['H']}` | {link(r['earlier'])} → {link(r['later'])} | {r['missed_dimension']} |")
md+=['','## Exclusions and chronology','', 'K1.1-correction-01 H4 `d69671168c0dcf5db6a7683d631027487c7520fe` has review-06 CHANGES REQUIRED and review-07 ACCEPT, in that record order. It is a same-H disagreement, not an ACCEPT→CHANGES REQUIRED chronology; examine both when transferring evidence. Ordinary failures on later changed H are not flips. The review-08 merged record carries both verdicts internally. The disclosed draft ACCEPTs have no independently recoverable draft text; this audit certifies the disclosure, not an absent review.','', '## For the next brief and reviewer','', '- State the input dimensions and cross-products to search, not only the seed cases: width × depth × invalidity × aliases × prototype shape × diagnostics. Distinguish single-root and eager multi-root work.','- Close producers against every downstream validator: identifier length, suffix growth, unrenderable text, replay, redelivery and inspection. Check every retained coordinate and the next positions.','- Vary comparison structure after parsing: element boundaries, duplicate rows, full-cell consumption, Unicode whitespace and enclosing Markdown context.','- Vary observation schedules and second-hop ambient accesses: coherent/incoherent reads, revoked objects, iterator results, callback reentrancy and species. Under a cooperative profile, explicitly declare hostile cases out of its guarantee and test the chosen wrapper separately.','- Compare a complete permitted decision: return, whole inspection, grants, history, receipt/refusal positions and delivery effects. Mutate the oracle and reject inconsistent combinations, not merely changed scalar projections.','- Interleave hidden and visible Executions to challenge scope-local evidence. Cross creation/input/Outcome namespaces.','- Inspect original B..H, C..H and any H..record payload; run appropriate cheap documentation/identity checks on H too. Candidate-local exclusions cannot authorize themselves.','- Check canonical owner, navigation, BASELINE, guides and ledger as different claims. A working link does not prove correct status prose.','- Transfer every surviving mutant with its mutation site, observation scope, expected distinguishing result and profile. “Suite failed” alone is not a kill unless failure is attributable to that obligation.','- Name how the claim finishes: bounded structural argument, specified oracle/check or explicitly delimited search. A faster timing sample never closes universal V-D1.']
stats={'evidence_rows':len(rows),'unique_H':len(set(r['H'] for r in rows)),'recorded_or_merged_unique_H':len(set(r['H'] for r in rows if 'recorded'==r['kind'] or r['kind'].startswith('recorded,') or r['kind']=='disclosed in merged record')),'cleanup_reopenings':sum(r['kind']=='cleanup reopening' for r in rows),'disclosed_unrecorded_drafts':sum(r['kind']=='disclosed unrecorded draft' for r in rows)}
for n,s in {'verdict-flips.md':'\n'.join(md)+'\n','verdict-flips-summary.json':json.dumps(stats,indent=2)+'\n'}.items():
 if '--check' in sys.argv:assert (P/n).read_text()==s,n
 else:(P/n).write_text(s)
print(json.dumps(stats,indent=2))
